CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_resnet'
MODEL: 'multi_person_posenet'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'output'
TAG: 'shelf_test/reset50/trained_using_asso4d'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'association4d_v2'
  TEST_DATASET: 'shelf'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  FLIP: False
  ROOT: '/home/tww/Downloads/Projects/Shelf' # 'data/panoptic/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX: 0
  CAMERA_NUM: 5
  NUM_JOINTS: 21
  IMAGE_WIDTH: 1032
  IMAGE_HEIGHT: 776
  NUM_FRAMES: 3200
  SMAPLE_INTERVAL: 2
NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_panoptic.pth.tar"
  PRETRAINED:  ''  # 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 800
  - 608
  HEATMAP_SIZE:
  - 200
  - 152
  SIGMA: 3
  NUM_JOINTS: 21
  USE_GT: False
POSE_RESNET:
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
  TRAIN_BACKBONE: true
  ENABLE_CACHE: false
TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 4
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: false
  SAVE_HEATMAPS_GT: false
  SAVE_HEATMAPS_PRED: true


MULTI_PERSON:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2000.0
  SPACE_CENTER:
    - 450.0 # 120.0
    - -320.0 # -600.0
    - 800.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 20
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.1
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
